version: '3'
services:
  db:
    image: awpc/postgres:9.6
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
        - PGDATA=/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    ports:
      - 5050:8080
    depends_on:
      - db
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    restart: on-failure
    depends_on:
      - db
    environment: 
      - DB_HOST=db
    volumes:
      - ../../platform:/platform:rw
    ports:
      - 3000:80
